baseURL: 'https://example.org'
#disableKinds:
# - page
# - section
# - taxonomy
# - term
module:
 mounts:
  - source: assets
    target: assets
  - source: hugo_stats.json
    target: assets/watching/hugo_stats.json
build:
 writeStats: true
 cachebusters:
  - source: assets/watching/hugo_stats\.json
    target: css
  - source: (postcss|tailwind)\.config\.js
    target: css
  - source: assets/.*\.(js|ts|jsx|tsx)
    target: js
