defaultDescription: Подробные инструкции по использованию сервиса, ответы на часто задаваемые вопросы от пользователей и разработчиков.
ogSiteName: Помощь Mail.ru
ogTitle: Помощь по сервисам Mail.ru
ogDescription: "Подробные инструкции по использованию сервисов Mail.ru: Почта, Облако, Календарь, Задачи, Заметки, VK Почта, Диск-О: и другие. Ответы на часто задаваемые вопросы."
topMailRuCounterID: ""
yandexMetrikaID: ""
xrayProject: "dev-help-mail-ru"
omicronID: "help_mail_ru"
